[package]
name = "p3-blake3"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
blake3 = { git = "https://github.com/npwardberkeley/BLAKE3" }
p3-symmetric = { path = "../symmetric" }
